import numpy as np
import qutip as qt
from qutip import Bloch, about, basis, sigmam,sigmax, sigmay, sigmaz, mesolve
import matplotlib.pyplot as plt

#----------- Simple setup ---------------------------------------------------#

# We will start with a simple model of an NV-center as a spin-1 system.
# In doing so we define H = [delta/2]sigmax 
# We define an additional collaps operator , describing the dissipation
# Of energy from the qubit to an external environment. C = [sqrt(g)]sigmaz

delta = 2* np.pi 

g = 0.25 

# Hamiltonian 
H = (delta/2) * sigmax()

# Collapse operators
c_ops = [np.sqrt(g) * sigmaz()]

# Initial state
psi0 = basis(2,0)  # Ground state

# Time vector
tlist = np.linspace(0, 5, 100)

#----------- Simple setup ---------------------------------------------------#



#----------- Passing values -------------------------------------------------#
res = mesolve(H,psi0,tlist,c_ops,[sigmaz()])

# For this perticular Hamiltonian and dissipation process , we can derive 
# The analytical solution for the expectation value of sigmaz

sz_analytical = np.cos(2*np.pi*tlist) * np.exp(-g*tlist)

#We can acces the expectation value generated by the mesolve by accesing res.expect[0]

#----------- Passing values -------------------------------------------------#


#----------- Plotting values ------------------------------------------------#

plt.scatter(tlist,res.expect[0],label='Numerical ',s=10)
plt.scatter(tlist, res.expect[0], c = "r", marker = "o", s = 10, label = "mesolve")

plt.plot(tlist,sz_analytical, label = "Analytical", c = "k")
plt.xlabel('Time'), plt.ylabel('<sigmaz>')
plt.legend()
plt.grid()
plt.show()

#----------- Plotting values -----------------------------------------------#